import type { Metadata } from "next";
import "./globals.css";
import { Provider } from  "./provider";
import Header from "./components/header";
import { Flip, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="lemonade">
      <Provider>
        <body>
          <Header/>
          {children}
          <ToastContainer autoClose={1000} transition={Flip} hideProgressBar={true} position="bottom-right" theme="colored" />
        </body>
      </Provider>
    </html>
  );
}
